CREATE DATABASE AgenciaViajes COLLATE utf8mb4_spanish_ci;

USE AgenciaViajes;

-- Tabla AGENCIA
CREATE TABLE Agencia(
    ID_AGENCIA INT PRIMARY KEY,
    COLOR CHAR(7), -- hexadecimal se guarda asi?
    NOMBRE VARCHAR(100),
    LOGO BLOB
);

-- Tabla EMPLEADO
CREATE TABLE Empleado(
    COD_EMPLE INT PRIMARY KEY,
    DESC_EMPLE VARCHAR(300),
    ID_AGENCIA INT,
		CONSTRAINT FK_ID_Agencia_Empleado FOREIGN KEY (ID_AGENCIA) REFERENCES Agencia(ID_AGENCIA)
);

-- Tabla TIPO_AGENCIA
CREATE TABLE Tipo_Agencia(
    ID_TIPO_AGENCIA INT PRIMARY KEY,
    DESC_AGENCIA VARCHAR(300),
    ID_AGENCIA INT,
		CONSTRAINT FK_ID_Agencia_Tipo_Agencia FOREIGN KEY (ID_AGENCIA) REFERENCES Agencia(ID_AGENCIA)
);

-- Tabla VIAJE
CREATE TABLE Viaje(
    ID_VIAJE INT PRIMARY KEY,
    NOM_VIAJE VARCHAR(100),
    DESC_VIAJE VARCHAR(300),
    NUM_DIAS INT,
    INI_VIAJE DATE,
    FIN_VIAJE DATE,
    SERV_NO_INC VARCHAR(300),
    ID_AGENCIA INT,
		CONSTRAINT FK_ID_Agencia_Viaje FOREIGN KEY (ID_AGENCIA) REFERENCES Agencia(ID_AGENCIA)
);

-- Tabla TIPO_VIAJE
CREATE TABLE Tipo_Viaje(
    ID_TIPO_VIAJE INT PRIMARY KEY,
    DESC_TIPO_VIAJE VARCHAR(300),
    ID_VIAJE INT,
		CONSTRAINT FK_ID_Viaje_Tipo_Viaje FOREIGN KEY (ID_VIAJE) REFERENCES Viaje(ID_VIAJE)
);

-- Tabla EVENTO
CREATE TABLE Evento(
    ID_EVENTO INT PRIMARY KEY,
    NOM_EVEN VARCHAR(100),
    ID_VIAJE INT,
		CONSTRAINT FK_ID_Viaje_Evento FOREIGN KEY (ID_VIAJE) REFERENCES Viaje(ID_VIAJE)
);

-- Tabla ACTIVIDAD
CREATE TABLE Actividad(
    COD_ACTIVIDAD INT,
    DESC_ACTIVIDAD VARCHAR(300),
    FECHA_ACT DATE,
    PRECIO_ACT DECIMAL(10, 2),
    ID_EVENTO INT,
		CONSTRAINT PK_COD_Actividad_ID_Evento PRIMARY KEY (COD_ACTIVIDAD, ID_EVENTO),
		CONSTRAINT FK_ID_Evento_Actividad FOREIGN KEY (ID_EVENTO) REFERENCES Evento(ID_EVENTO)
);

-- Tabla ALOJAMIENTO
CREATE TABLE Alojamiento(
    COD_HOT INT,
    CIUDAD VARCHAR(100),
    FECHA DATE,
    PRECIO DECIMAL(10, 2),
    ID_EVENTO INT,
		CONSTRAINT PK_COD_Hot_ID_Evento PRIMARY KEY (COD_HOT, ID_EVENTO),
		CONSTRAINT FK_ID_Evento_Alojamiento FOREIGN KEY (ID_EVENTO) REFERENCES Evento(ID_EVENTO)
);

-- Tabla TIPO_HABITACION
CREATE TABLE Tipo_Habitacion(
    ID_TIPO_HAB INT,
    DESC_HABITACION VARCHAR(255),
    ID_EVENTO INT,
		CONSTRAINT PK_ID_Tipo_Hab_ID_Evento PRIMARY KEY (ID_TIPO_HAB, ID_EVENTO),
		CONSTRAINT FK_ID_Evento_Tipo_Habitacion FOREIGN KEY (ID_EVENTO) REFERENCES Evento(ID_EVENTO)
);

-- Tabla VUELO
CREATE TABLE Vuelo(
    COD_VUELO INT PRIMARY KEY,
    AER_ORIGEN VARCHAR(100),
    AER_DEST VARCHAR(100),
    AEROLINEA VARCHAR(100),
    PRECIO_TOTAL DECIMAL(10, 2),
    FECHA_SAL DATE,
    HORA_SAL TIME,
    DURACION TIME,
    ID_EVENTO INT,
		CONSTRAINT FK_ID_Evento_Vuelo FOREIGN KEY (ID_EVENTO) REFERENCES Evento(ID_EVENTO)
);

-- Tabla VUELO_AEROPUERTO
CREATE TABLE Vuelo_Aeropuerto(
    COD_VUELO INT,
    COD_AEROPUERTO INT,
		CONSTRAINT PK_COD_Vuelo_COD_Aeropuerto PRIMARY KEY (COD_VUELO, COD_AEROPUERTO),
		CONSTRAINT FK_COD_Vuelo_Vuelo_Aeropuerto FOREIGN KEY (COD_VUELO) REFERENCES Vuelo(COD_VUELO),
		CONSTRAINT FK_COD_Aeropuerto_Vuelo_Aeropuerto FOREIGN KEY (COD_AEROPUERTO) REFERENCES Aeropuerto(COD_AEROPUERTO)
);

-- Tabla IDA_Y_VUELTA
CREATE TABLE Ida_Y_Vuelta(
    FEC_REGRESO DATE,
    HORA_VUELTA TIME,
    COD_VUELO INT,
    COD_AEROLINEA INT,
		CONSTRAINT PK_COD_Vuelo_COD_Aerolinea PRIMARY KEY (COD_VUELO, COD_AEROLINEA),
		CONSTRAINT FK_COD_Vuelo_Ida_Y_Vuelta FOREIGN KEY (COD_VUELO) REFERENCES Vuelo(COD_VUELO),
		CONSTRAINT FK_COD_Aerolinea_Ida_Y_Vuelta FOREIGN KEY (COD_AEROLINEA) REFERENCES Aerolinea(COD_AEROLINEA)
);

-- Tabla IDA
CREATE TABLE Ida(
    HORA_SALIDA TIME,
    COD_VUELO INT,
    COD_AEROLINEA INT,
		CONSTRAINT PK_COD_Vuelo_COD_Aerolinea_Ida PRIMARY KEY (COD_VUELO, COD_AEROLINEA),
		CONSTRAINT FK_COD_Vuelo_Ida FOREIGN KEY (COD_VUELO) REFERENCES Vuelo(COD_VUELO),
		CONSTRAINT FK_COD_Aerolinea_Ida FOREIGN KEY (COD_AEROLINEA) REFERENCES Aerolinea(COD_AEROLINEA)
);

-- Tabla AEROLINEA
CREATE TABLE Aerolinea(
    COD_AEROLINEA INT PRIMARY KEY,
    NOMBRE VARCHAR(100),
    COD_PAIS INT,
		CONSTRAINT FK_COD_Pais_Aerolinea FOREIGN KEY (COD_PAIS) REFERENCES Pais(COD_PAIS)
);

-- Tabla PAIS
CREATE TABLE Pais(
    COD_PAIS INT PRIMARY KEY,
    NOMBRE VARCHAR(100)
);

-- Tabla AEROPUERTO
CREATE TABLE Aeropuerto(
    COD_AEROPUERTO INT PRIMARY KEY,
    CIUDAD VARCHAR(100),
    COD_PAIS INT,
		CONSTRAINT FK_COD_Pais_Aeropuerto FOREIGN KEY (COD_PAIS) REFERENCES Pais(COD_PAIS)
);
